server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/ldp
    username: root
    password: 1234567890987654321
  mvc:
    hiddenmethod:
      filter:
        enabled: true
mybatis:
  type-aliases-package: work.huangxin.mango.model
  mapper-locations: classpath:mappers/*.xml
  #通用mapper配置
  mapper:
    #公用接口类路径
    mappers: work.huangxin.mango.basemapper
    identity: MYSQL

logging:
  level:
    work.huangxin.mango.mapper: debug

spring.jackson.date-format: yyyy-MM-dd HH:mm

#这个是时区，一定要加，否则会默认为格林尼治时间，即少8小时
spring.jackson.time-zone: GMT+8
#
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
